In [1]:
import tensorflow as tf
import numpy as np
import pickle
from sklearn.metrics import confusion_matrix
import seaborn as sn
import pandas as pd
import matplotlib.pyplot as plt

C:\Users\djaym7\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def loadData(id):
    with open(f'y_train_{id}','rb') as f:
        y_train=np.array(pickle.load(f))
    with open(f'y_test_{id}','rb') as f:
        y_test=np.array(pickle.load(f))
    with open(f'X_train_{id}','rb') as f:
        X_train = np.array(pickle.load(f))
    with open(f'X_test_{id}','rb') as f:
        X_test = np.array(pickle.load(f))

    

    from sklearn.preprocessing import LabelBinarizer
    encoder = LabelBinarizer()
    y_train = encoder.fit_transform(y_train)
    y_test = encoder.fit_transform(y_test)


    print('X_train:',X_train.shape)
    print('X_test:',X_test.shape)
    print('y_train',y_train.shape) 
    print('y_test',y_test.shape) 

   
    return X_train,y_train,X_test,y_test


In [3]:
'''
#changing model layers/params #2
from attention import attention
# Trying attention

X = tf.placeholder(dtype=tf.float32,name='X',shape=(None,369,20))
y = tf.placeholder(dtype=tf.int32,name='y',shape=(None,6))


cell0 = tf.nn.rnn_cell.LSTMCell(num_units=64,activation=tf.nn.tanh,dtype=tf.float32,name='lstm0')
cell0= tf.nn.rnn_cell.DropoutWrapper(cell0,output_keep_prob=0.5)
output0,states0 = tf.nn.dynamic_rnn(cell0,X,dtype=tf.float32,swap_memory=True)


cell1 = tf.nn.rnn_cell.LSTMCell(num_units=128,activation=tf.nn.tanh,dtype=tf.float32,name='lstm1')
cell1= tf.nn.rnn_cell.DropoutWrapper(cell1,output_keep_prob=0.5)
output1,states1 = tf.nn.dynamic_rnn(cell1,output0,dtype=tf.float32,swap_memory=True)


cell2 = tf.nn.rnn_cell.LSTMCell(num_units=128,activation=tf.nn.tanh,dtype=tf.float32,name='lstm2')
cell2= tf.nn.rnn_cell.DropoutWrapper(cell2,output_keep_prob=0.5)
output2,states2 = tf.nn.dynamic_rnn(cell2,output1,dtype=tf.float32,swap_memory=True)

attention_output, alphas = attention(output2, 50, return_alphas=True)
drop = tf.nn.dropout(attention_output,keep_prob=0.5)

attention_states = tf.multiply(drop,states2[0]) #CONTEXT INSTEAD OF HS

cell3 = tf.layers.dense(units=128,activation=tf.nn.relu,inputs=attention_states,name='dense')
cell4 = tf.layers.dense(units=6,activation=None,inputs=cell3,name='dense2')


loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=cell4,labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
training_op = optimizer.minimize(loss)
correct_prediction = tf.equal(tf.argmax(cell4, 1), tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
#init = tf.global_variables_initializer()
'''


"\n#changing model layers/params #2\nfrom attention import attention\n# Trying attention\n\nX = tf.placeholder(dtype=tf.float32,name='X',shape=(None,369,20))\ny = tf.placeholder(dtype=tf.int32,name='y',shape=(None,6))\n\n\ncell0 = tf.nn.rnn_cell.LSTMCell(num_units=64,activation=tf.nn.tanh,dtype=tf.float32,name='lstm0')\ncell0= tf.nn.rnn_cell.DropoutWrapper(cell0,output_keep_prob=0.5)\noutput0,states0 = tf.nn.dynamic_rnn(cell0,X,dtype=tf.float32,swap_memory=True)\n\n\ncell1 = tf.nn.rnn_cell.LSTMCell(num_units=128,activation=tf.nn.tanh,dtype=tf.float32,name='lstm1')\ncell1= tf.nn.rnn_cell.DropoutWrapper(cell1,output_keep_prob=0.5)\noutput1,states1 = tf.nn.dynamic_rnn(cell1,output0,dtype=tf.float32,swap_memory=True)\n\n\ncell2 = tf.nn.rnn_cell.LSTMCell(num_units=128,activation=tf.nn.tanh,dtype=tf.float32,name='lstm2')\ncell2= tf.nn.rnn_cell.DropoutWrapper(cell2,output_keep_prob=0.5)\noutput2,states2 = tf.nn.dynamic_rnn(cell2,output1,dtype=tf.float32,swap_memory=True)\n\nattention_output, 

In [4]:
def result(y_pred,y_test,plot=False):
    y_pred_final=[] #getting final answers 
    y_test_final=[]
    for i in range((y_pred.shape[0])):
        y_pred_final.append(np.argmax(y_pred[i]))
        y_test_final.append(np.argmax(y_test[i]))

    y_pred_final_alpha=[]
    y_test_final_alpha=[]


    from sklearn.metrics import confusion_matrix,accuracy_score
    confusion_matrix = confusion_matrix(y_test_final,y_pred_final,labels=[0,1,2,3,4,5])
    print(confusion_matrix)
    print(accuracy_score(y_test_final,y_pred_final))


    #plot confusion matrix
    
    if plot == True:
        df_confusion_matrix  = pd.DataFrame(array)
        plt.figure(figsize = (10,10))
        plt.show()
        sn.heatmap(df_confusion_matrix, annot=True)
    return confusion_matrix

In [ ]:

total_num_people=[]
for i in range(1,92):
    if i <10:
        total_num_people.append('100'+str(i))
    else:
        total_num_people.append('10'+str(i))
epochs = 80
batch_size = 370
results = []
confusionMatrix=[]
for i in total_num_people:
    X_train=[]
    X_test=[]
    y_train=[]
    y_test=[]
    X_train,y_train,X_test,y_test=loadData(i)
    

################################################### MODEL ##################################################################
    from attention import attention
    # Trying attention

    X = tf.placeholder(dtype=tf.float32,name='X',shape=(None,369,20))
    y = tf.placeholder(dtype=tf.int32,name='y',shape=(None,6))


    cell0 = tf.nn.rnn_cell.LSTMCell(num_units=64,activation=tf.nn.tanh,dtype=tf.float32,name='lstm0')
    cell0= tf.nn.rnn_cell.DropoutWrapper(cell0,output_keep_prob=0.5)
    output0,states0 = tf.nn.dynamic_rnn(cell0,X,dtype=tf.float32,swap_memory=True)


    cell1 = tf.nn.rnn_cell.LSTMCell(num_units=128,activation=tf.nn.tanh,dtype=tf.float32,name='lstm1')
    cell1= tf.nn.rnn_cell.DropoutWrapper(cell1,output_keep_prob=0.5)
    output1,states1 = tf.nn.dynamic_rnn(cell1,output0,dtype=tf.float32,swap_memory=True)


    cell2 = tf.nn.rnn_cell.LSTMCell(num_units=128,activation=tf.nn.tanh,dtype=tf.float32,name='lstm2')
    cell2= tf.nn.rnn_cell.DropoutWrapper(cell2,output_keep_prob=0.5)
    output2,states2 = tf.nn.dynamic_rnn(cell2,output1,dtype=tf.float32,swap_memory=True)

    attention_output, alphas = attention(output2, 50, return_alphas=True)
    drop = tf.nn.dropout(attention_output,keep_prob=0.5)

    attention_states = tf.multiply(drop,states2[0]) #CONTEXT INSTEAD OF HS

    cell3 = tf.layers.dense(units=128,activation=tf.nn.relu,inputs=attention_states,name='dense')
    cell4 = tf.layers.dense(units=6,activation=None,inputs=cell3,name='dense2')


    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=cell4,labels=y))
    optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
    training_op = optimizer.minimize(loss)
    
    correct_prediction = tf.equal(tf.argmax(cell4, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    #init = tf.global_variables_initializer()
    predict = cell4

    
############################################################################################################################    
    
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for epoch_no in range(epochs):
            for index, offset in enumerate(range(0, X_train.shape[0], batch_size)):
                xs, ys = X_train[offset: offset + batch_size], y_train[offset: offset + batch_size]
                sess.run(training_op, feed_dict={X: xs, y: ys})
                y_pred=sess.run(predict,feed_dict={X:X_test})

                
            los, acc = sess.run([loss, accuracy], feed_dict = {X: xs, y: ys})
            val_los, val_acc = sess.run([loss, accuracy], feed_dict = {X: X_test, y: y_test})
            print (f'id {i} epoch {epoch_no} index {index}, Loss: {los:.4f}, accuracy = {acc:.4f}, Val_loss ={val_los:.4f} , val_acc ={val_acc:.4f}')
    current_confusion_Mat = result(y_pred,y_test)
    confusionMatrix.append(current_confusion_Mat)
    results.append((val_los,val_acc))
    tf.reset_default_graph()

        


X_train: (7360, 369, 20)
X_test: (82, 369, 20)
y_train (7360, 6)
y_test (82, 6)
id 1001 epoch 0 index 19, Loss: 1.5537, accuracy = 0.3515, Val_loss =1.6431 , val_acc =0.2683
id 1001 epoch 1 index 19, Loss: 1.3875, accuracy = 0.4394, Val_loss =1.9499 , val_acc =0.1707
id 1001 epoch 2 index 19, Loss: 1.4392, accuracy = 0.4182, Val_loss =1.9444 , val_acc =0.1463
id 1001 epoch 3 index 19, Loss: 1.3576, accuracy = 0.4788, Val_loss =1.8071 , val_acc =0.1951
id 1001 epoch 4 index 19, Loss: 1.3449, accuracy = 0.4364, Val_loss =1.7335 , val_acc =0.2317
id 1001 epoch 5 index 19, Loss: 1.3099, accuracy = 0.4545, Val_loss =1.8497 , val_acc =0.1829
id 1001 epoch 6 index 19, Loss: 1.2778, accuracy = 0.5000, Val_loss =1.6056 , val_acc =0.2317
id 1001 epoch 7 index 19, Loss: 1.2850, accuracy = 0.4970, Val_loss =1.6318 , val_acc =0.2073
id 1001 epoch 8 index 19, Loss: 1.2498, accuracy = 0.5242, Val_loss =1.7704 , val_acc =0.2073
id 1001 epoch 9 index 19, Loss: 1.2285, accuracy = 0.5364, Val_loss =1.774

id 1002 epoch 4 index 19, Loss: 1.3430, accuracy = 0.4773, Val_loss =1.4617 , val_acc =0.4444
id 1002 epoch 5 index 19, Loss: 1.3477, accuracy = 0.4562, Val_loss =1.4748 , val_acc =0.3951
id 1002 epoch 6 index 19, Loss: 1.3105, accuracy = 0.4804, Val_loss =1.4855 , val_acc =0.3951
id 1002 epoch 7 index 19, Loss: 1.3099, accuracy = 0.4713, Val_loss =1.4630 , val_acc =0.4074
id 1002 epoch 8 index 19, Loss: 1.2963, accuracy = 0.4924, Val_loss =1.5023 , val_acc =0.3951
id 1002 epoch 9 index 19, Loss: 1.2321, accuracy = 0.5166, Val_loss =1.4271 , val_acc =0.4444
id 1002 epoch 10 index 19, Loss: 1.2395, accuracy = 0.5015, Val_loss =1.4505 , val_acc =0.4444
id 1002 epoch 11 index 19, Loss: 1.2573, accuracy = 0.5076, Val_loss =1.4367 , val_acc =0.4815
id 1002 epoch 12 index 19, Loss: 1.1808, accuracy = 0.5468, Val_loss =1.5035 , val_acc =0.4444
id 1002 epoch 13 index 19, Loss: 1.1662, accuracy = 0.5589, Val_loss =1.5346 , val_acc =0.3827
id 1002 epoch 14 index 19, Loss: 1.1658, accuracy = 0.52

id 1003 epoch 9 index 19, Loss: 1.2117, accuracy = 0.5121, Val_loss =1.2030 , val_acc =0.5000
id 1003 epoch 10 index 19, Loss: 1.2358, accuracy = 0.5152, Val_loss =1.1542 , val_acc =0.6585
id 1003 epoch 11 index 19, Loss: 1.1976, accuracy = 0.5455, Val_loss =1.3135 , val_acc =0.5122
id 1003 epoch 12 index 19, Loss: 1.1938, accuracy = 0.5364, Val_loss =1.1894 , val_acc =0.5366
id 1003 epoch 13 index 19, Loss: 1.1773, accuracy = 0.5424, Val_loss =1.1175 , val_acc =0.6098
id 1003 epoch 14 index 19, Loss: 1.2215, accuracy = 0.5212, Val_loss =1.1635 , val_acc =0.5610
id 1003 epoch 15 index 19, Loss: 1.2230, accuracy = 0.5212, Val_loss =1.1363 , val_acc =0.5366
id 1003 epoch 16 index 19, Loss: 1.1912, accuracy = 0.5515, Val_loss =1.1385 , val_acc =0.5244
id 1003 epoch 17 index 19, Loss: 1.1608, accuracy = 0.5545, Val_loss =1.1922 , val_acc =0.5366
id 1003 epoch 18 index 19, Loss: 1.1469, accuracy = 0.5455, Val_loss =1.1704 , val_acc =0.4878
id 1003 epoch 19 index 19, Loss: 1.1279, accuracy =

id 1004 epoch 13 index 19, Loss: 1.1674, accuracy = 0.5636, Val_loss =1.3297 , val_acc =0.4634
id 1004 epoch 14 index 19, Loss: 1.1460, accuracy = 0.5485, Val_loss =1.3245 , val_acc =0.4756
id 1004 epoch 15 index 19, Loss: 1.0791, accuracy = 0.5788, Val_loss =1.4529 , val_acc =0.3902
id 1004 epoch 16 index 19, Loss: 1.0746, accuracy = 0.6182, Val_loss =1.2057 , val_acc =0.5610
id 1004 epoch 17 index 19, Loss: 1.0853, accuracy = 0.6152, Val_loss =1.3324 , val_acc =0.4390
id 1004 epoch 18 index 19, Loss: 1.0924, accuracy = 0.5879, Val_loss =1.3977 , val_acc =0.4146
id 1004 epoch 19 index 19, Loss: 1.0349, accuracy = 0.6182, Val_loss =1.2900 , val_acc =0.4634
id 1004 epoch 20 index 19, Loss: 1.0697, accuracy = 0.5939, Val_loss =1.4109 , val_acc =0.4268
id 1004 epoch 21 index 19, Loss: 1.0447, accuracy = 0.6182, Val_loss =1.2729 , val_acc =0.5122
id 1004 epoch 22 index 19, Loss: 1.0382, accuracy = 0.6121, Val_loss =1.5293 , val_acc =0.4146
id 1004 epoch 23 index 19, Loss: 1.0326, accuracy 

id 1005 epoch 17 index 19, Loss: 1.1012, accuracy = 0.5667, Val_loss =1.2346 , val_acc =0.5244
id 1005 epoch 18 index 19, Loss: 1.1228, accuracy = 0.5697, Val_loss =1.2721 , val_acc =0.4756
id 1005 epoch 19 index 19, Loss: 1.0961, accuracy = 0.6061, Val_loss =1.2779 , val_acc =0.4512
id 1005 epoch 20 index 19, Loss: 1.1024, accuracy = 0.5909, Val_loss =1.2472 , val_acc =0.5366
id 1005 epoch 21 index 19, Loss: 1.0487, accuracy = 0.6030, Val_loss =1.2600 , val_acc =0.5732
id 1005 epoch 22 index 19, Loss: 1.0292, accuracy = 0.6364, Val_loss =1.2617 , val_acc =0.4878
id 1005 epoch 23 index 19, Loss: 1.0433, accuracy = 0.6212, Val_loss =1.2502 , val_acc =0.5122
id 1005 epoch 24 index 19, Loss: 1.0618, accuracy = 0.6061, Val_loss =1.3273 , val_acc =0.4024
id 1005 epoch 25 index 19, Loss: 1.0764, accuracy = 0.6000, Val_loss =1.2500 , val_acc =0.4756
id 1005 epoch 26 index 19, Loss: 0.9958, accuracy = 0.6242, Val_loss =1.2148 , val_acc =0.5000
id 1005 epoch 27 index 19, Loss: 1.0096, accuracy 

id 1006 epoch 21 index 19, Loss: 1.0635, accuracy = 0.6000, Val_loss =1.2171 , val_acc =0.5000
id 1006 epoch 22 index 19, Loss: 1.0843, accuracy = 0.5667, Val_loss =1.2192 , val_acc =0.5976
id 1006 epoch 23 index 19, Loss: 1.1274, accuracy = 0.5545, Val_loss =1.2926 , val_acc =0.5122
id 1006 epoch 24 index 19, Loss: 1.1335, accuracy = 0.5909, Val_loss =1.5175 , val_acc =0.5244
id 1006 epoch 25 index 19, Loss: 1.0833, accuracy = 0.5818, Val_loss =1.1538 , val_acc =0.5732
id 1006 epoch 26 index 19, Loss: 1.1000, accuracy = 0.5697, Val_loss =1.1268 , val_acc =0.5488
id 1006 epoch 27 index 19, Loss: 1.0630, accuracy = 0.6152, Val_loss =1.1865 , val_acc =0.5976
id 1006 epoch 28 index 19, Loss: 1.0679, accuracy = 0.6121, Val_loss =1.1511 , val_acc =0.5854
id 1006 epoch 29 index 19, Loss: 1.0463, accuracy = 0.6212, Val_loss =1.0401 , val_acc =0.5732
id 1006 epoch 30 index 19, Loss: 1.0487, accuracy = 0.6182, Val_loss =1.3970 , val_acc =0.5610
id 1006 epoch 31 index 19, Loss: 1.0187, accuracy 

id 1007 epoch 25 index 19, Loss: 1.1240, accuracy = 0.5606, Val_loss =1.4305 , val_acc =0.4024
id 1007 epoch 26 index 19, Loss: 1.0573, accuracy = 0.6061, Val_loss =1.3815 , val_acc =0.4756
id 1007 epoch 27 index 19, Loss: 1.0726, accuracy = 0.5848, Val_loss =1.4669 , val_acc =0.4756
id 1007 epoch 28 index 19, Loss: 1.0619, accuracy = 0.5848, Val_loss =1.4914 , val_acc =0.4146
id 1007 epoch 29 index 19, Loss: 1.0497, accuracy = 0.6061, Val_loss =1.5211 , val_acc =0.4024
id 1007 epoch 30 index 19, Loss: 1.0132, accuracy = 0.6273, Val_loss =1.5875 , val_acc =0.4756
id 1007 epoch 31 index 19, Loss: 1.1158, accuracy = 0.5697, Val_loss =1.4274 , val_acc =0.4512
id 1007 epoch 32 index 19, Loss: 1.0808, accuracy = 0.5909, Val_loss =1.5014 , val_acc =0.4756
id 1007 epoch 33 index 19, Loss: 0.9934, accuracy = 0.6424, Val_loss =1.4580 , val_acc =0.5244
id 1007 epoch 34 index 19, Loss: 0.9927, accuracy = 0.6485, Val_loss =1.5294 , val_acc =0.3659
id 1007 epoch 35 index 19, Loss: 1.0239, accuracy 

id 1008 epoch 29 index 19, Loss: 1.0105, accuracy = 0.6250, Val_loss =1.5869 , val_acc =0.4605
id 1008 epoch 30 index 19, Loss: 1.0430, accuracy = 0.6071, Val_loss =1.3443 , val_acc =0.5000
id 1008 epoch 31 index 19, Loss: 1.0813, accuracy = 0.5863, Val_loss =1.4300 , val_acc =0.5000
id 1008 epoch 32 index 19, Loss: 1.0218, accuracy = 0.5982, Val_loss =1.5304 , val_acc =0.4605
id 1008 epoch 33 index 19, Loss: 1.0633, accuracy = 0.5893, Val_loss =1.3766 , val_acc =0.4605
id 1008 epoch 34 index 19, Loss: 1.0421, accuracy = 0.6280, Val_loss =1.4771 , val_acc =0.4737
id 1008 epoch 35 index 19, Loss: 1.0079, accuracy = 0.6250, Val_loss =1.3944 , val_acc =0.4605
id 1008 epoch 36 index 19, Loss: 0.9809, accuracy = 0.6339, Val_loss =1.5568 , val_acc =0.5000
id 1008 epoch 37 index 19, Loss: 1.0049, accuracy = 0.6250, Val_loss =1.4700 , val_acc =0.4605
id 1008 epoch 38 index 19, Loss: 0.9804, accuracy = 0.6399, Val_loss =1.5336 , val_acc =0.4868
id 1008 epoch 39 index 19, Loss: 0.9849, accuracy 

id 1009 epoch 34 index 19, Loss: 0.9969, accuracy = 0.5863, Val_loss =1.0320 , val_acc =0.6842
id 1009 epoch 35 index 19, Loss: 0.9680, accuracy = 0.6458, Val_loss =0.9768 , val_acc =0.6053
id 1009 epoch 36 index 19, Loss: 1.0105, accuracy = 0.6339, Val_loss =1.0915 , val_acc =0.5789
id 1009 epoch 37 index 19, Loss: 0.9560, accuracy = 0.6369, Val_loss =1.0026 , val_acc =0.6447
id 1009 epoch 38 index 19, Loss: 0.9460, accuracy = 0.6429, Val_loss =1.0098 , val_acc =0.6316
id 1009 epoch 39 index 19, Loss: 0.9699, accuracy = 0.6429, Val_loss =1.1116 , val_acc =0.6184
id 1009 epoch 40 index 19, Loss: 0.9515, accuracy = 0.6488, Val_loss =0.9898 , val_acc =0.6316
id 1009 epoch 41 index 19, Loss: 0.9265, accuracy = 0.6548, Val_loss =1.0264 , val_acc =0.6316
id 1009 epoch 42 index 19, Loss: 0.9341, accuracy = 0.6667, Val_loss =1.2250 , val_acc =0.6842
id 1009 epoch 43 index 19, Loss: 0.9620, accuracy = 0.6548, Val_loss =1.0601 , val_acc =0.6447
id 1009 epoch 44 index 19, Loss: 0.8994, accuracy 

id 1010 epoch 38 index 19, Loss: 1.0248, accuracy = 0.6242, Val_loss =1.1017 , val_acc =0.5244
id 1010 epoch 39 index 19, Loss: 0.9280, accuracy = 0.6667, Val_loss =1.1029 , val_acc =0.5488
id 1010 epoch 40 index 19, Loss: 0.9248, accuracy = 0.6364, Val_loss =1.0722 , val_acc =0.5488
id 1010 epoch 41 index 19, Loss: 0.8651, accuracy = 0.6758, Val_loss =1.1033 , val_acc =0.5732
id 1010 epoch 42 index 19, Loss: 0.8621, accuracy = 0.6970, Val_loss =1.2851 , val_acc =0.5000
id 1010 epoch 43 index 19, Loss: 0.9378, accuracy = 0.6576, Val_loss =1.3043 , val_acc =0.4756
id 1010 epoch 44 index 19, Loss: 0.9749, accuracy = 0.6455, Val_loss =1.0883 , val_acc =0.5366
id 1010 epoch 45 index 19, Loss: 0.8835, accuracy = 0.6727, Val_loss =1.0266 , val_acc =0.6098
id 1010 epoch 46 index 19, Loss: 0.8869, accuracy = 0.6697, Val_loss =1.1783 , val_acc =0.5366
id 1010 epoch 47 index 19, Loss: 0.8811, accuracy = 0.6879, Val_loss =1.0554 , val_acc =0.5732
id 1010 epoch 48 index 19, Loss: 0.8971, accuracy 

id 1011 epoch 42 index 19, Loss: 0.9275, accuracy = 0.6758, Val_loss =1.1374 , val_acc =0.6341
id 1011 epoch 43 index 19, Loss: 0.9058, accuracy = 0.6424, Val_loss =1.1171 , val_acc =0.6098
id 1011 epoch 44 index 19, Loss: 0.9440, accuracy = 0.6455, Val_loss =1.0986 , val_acc =0.6463
id 1011 epoch 45 index 19, Loss: 0.9722, accuracy = 0.6424, Val_loss =1.1730 , val_acc =0.6220
id 1011 epoch 46 index 19, Loss: 0.9452, accuracy = 0.6455, Val_loss =1.2048 , val_acc =0.5732
id 1011 epoch 47 index 19, Loss: 0.9622, accuracy = 0.6303, Val_loss =1.1878 , val_acc =0.5854
id 1011 epoch 48 index 19, Loss: 0.8843, accuracy = 0.6545, Val_loss =1.2646 , val_acc =0.5732
id 1011 epoch 49 index 19, Loss: 0.8682, accuracy = 0.6909, Val_loss =1.2274 , val_acc =0.6098
id 1011 epoch 50 index 19, Loss: 0.8390, accuracy = 0.6697, Val_loss =0.9103 , val_acc =0.7195
id 1011 epoch 51 index 19, Loss: 0.8438, accuracy = 0.6788, Val_loss =1.1541 , val_acc =0.6341
id 1011 epoch 52 index 19, Loss: 0.8572, accuracy 

id 1012 epoch 46 index 19, Loss: 0.9267, accuracy = 0.6515, Val_loss =1.2556 , val_acc =0.5732
id 1012 epoch 47 index 19, Loss: 0.8732, accuracy = 0.6788, Val_loss =1.0667 , val_acc =0.6220
id 1012 epoch 48 index 19, Loss: 0.8680, accuracy = 0.6727, Val_loss =1.1080 , val_acc =0.5976
id 1012 epoch 49 index 19, Loss: 0.8634, accuracy = 0.6818, Val_loss =1.1937 , val_acc =0.5732
id 1012 epoch 50 index 19, Loss: 0.8575, accuracy = 0.6606, Val_loss =1.2247 , val_acc =0.5610
id 1012 epoch 51 index 19, Loss: 0.8641, accuracy = 0.6576, Val_loss =1.1271 , val_acc =0.5976
id 1012 epoch 52 index 19, Loss: 0.8304, accuracy = 0.7000, Val_loss =1.1059 , val_acc =0.6220
id 1012 epoch 53 index 19, Loss: 0.8390, accuracy = 0.6727, Val_loss =1.3017 , val_acc =0.5366
id 1012 epoch 54 index 19, Loss: 0.8725, accuracy = 0.6455, Val_loss =1.0712 , val_acc =0.6341
id 1012 epoch 55 index 19, Loss: 0.7818, accuracy = 0.7000, Val_loss =1.0825 , val_acc =0.6098
id 1012 epoch 56 index 19, Loss: 0.8222, accuracy 

id 1013 epoch 50 index 19, Loss: 0.9091, accuracy = 0.6818, Val_loss =0.9225 , val_acc =0.5732
id 1013 epoch 51 index 19, Loss: 0.8776, accuracy = 0.6970, Val_loss =0.8197 , val_acc =0.6098
id 1013 epoch 52 index 19, Loss: 0.8673, accuracy = 0.6758, Val_loss =0.7508 , val_acc =0.6707
id 1013 epoch 53 index 19, Loss: 0.8744, accuracy = 0.6697, Val_loss =0.7810 , val_acc =0.6341
id 1013 epoch 54 index 19, Loss: 0.8554, accuracy = 0.6818, Val_loss =0.7987 , val_acc =0.6707
id 1013 epoch 55 index 19, Loss: 0.8410, accuracy = 0.6939, Val_loss =0.8212 , val_acc =0.5976
id 1013 epoch 56 index 19, Loss: 0.8417, accuracy = 0.6758, Val_loss =0.8874 , val_acc =0.6341
id 1013 epoch 57 index 19, Loss: 0.8141, accuracy = 0.6970, Val_loss =0.8948 , val_acc =0.6463
id 1013 epoch 58 index 19, Loss: 0.8558, accuracy = 0.6848, Val_loss =0.8739 , val_acc =0.6585
id 1013 epoch 59 index 19, Loss: 0.8283, accuracy = 0.7000, Val_loss =0.9089 , val_acc =0.5976
id 1013 epoch 60 index 19, Loss: 0.8429, accuracy 

id 1014 epoch 54 index 19, Loss: 0.9073, accuracy = 0.6576, Val_loss =1.0556 , val_acc =0.6463
id 1014 epoch 55 index 19, Loss: 0.8939, accuracy = 0.6848, Val_loss =1.0237 , val_acc =0.6829
id 1014 epoch 56 index 19, Loss: 0.8883, accuracy = 0.6818, Val_loss =1.0019 , val_acc =0.6707
id 1014 epoch 57 index 19, Loss: 0.9008, accuracy = 0.6606, Val_loss =1.0786 , val_acc =0.6463
id 1014 epoch 58 index 19, Loss: 0.8531, accuracy = 0.6697, Val_loss =1.0684 , val_acc =0.6220
id 1014 epoch 59 index 19, Loss: 0.8427, accuracy = 0.6788, Val_loss =1.2852 , val_acc =0.5610
id 1014 epoch 60 index 19, Loss: 0.8221, accuracy = 0.7152, Val_loss =1.1891 , val_acc =0.5732
id 1014 epoch 61 index 19, Loss: 0.8489, accuracy = 0.6970, Val_loss =1.2141 , val_acc =0.6463
id 1014 epoch 62 index 19, Loss: 0.7842, accuracy = 0.7030, Val_loss =1.4791 , val_acc =0.6220
id 1014 epoch 63 index 19, Loss: 0.8260, accuracy = 0.7000, Val_loss =1.5146 , val_acc =0.5976
id 1014 epoch 64 index 19, Loss: 0.8120, accuracy 

id 1015 epoch 58 index 19, Loss: 0.7965, accuracy = 0.7061, Val_loss =1.7325 , val_acc =0.4268
id 1015 epoch 59 index 19, Loss: 0.7658, accuracy = 0.7030, Val_loss =1.7202 , val_acc =0.4756
id 1015 epoch 60 index 19, Loss: 0.7410, accuracy = 0.7273, Val_loss =1.6246 , val_acc =0.4878
id 1015 epoch 61 index 19, Loss: 0.8028, accuracy = 0.6848, Val_loss =1.5890 , val_acc =0.4878
id 1015 epoch 62 index 19, Loss: 0.8225, accuracy = 0.6879, Val_loss =1.5344 , val_acc =0.4878
id 1015 epoch 63 index 19, Loss: 0.7444, accuracy = 0.7242, Val_loss =1.3609 , val_acc =0.5244
id 1015 epoch 64 index 19, Loss: 0.7024, accuracy = 0.7455, Val_loss =1.3881 , val_acc =0.5122
id 1015 epoch 65 index 19, Loss: 0.7067, accuracy = 0.7152, Val_loss =1.4636 , val_acc =0.5244
id 1015 epoch 66 index 19, Loss: 0.6775, accuracy = 0.7515, Val_loss =1.6749 , val_acc =0.4634
id 1015 epoch 67 index 19, Loss: 0.6601, accuracy = 0.7364, Val_loss =1.3670 , val_acc =0.5366
id 1015 epoch 68 index 19, Loss: 0.7291, accuracy 

id 1016 epoch 62 index 19, Loss: 0.9125, accuracy = 0.6848, Val_loss =1.2487 , val_acc =0.4512
id 1016 epoch 63 index 19, Loss: 0.9503, accuracy = 0.6636, Val_loss =1.1282 , val_acc =0.5244
id 1016 epoch 64 index 19, Loss: 0.8880, accuracy = 0.6970, Val_loss =1.3883 , val_acc =0.4756
id 1016 epoch 65 index 19, Loss: 0.8665, accuracy = 0.7091, Val_loss =1.2208 , val_acc =0.5488
id 1016 epoch 66 index 19, Loss: 0.8757, accuracy = 0.6818, Val_loss =1.1176 , val_acc =0.5610
id 1016 epoch 67 index 19, Loss: 0.8562, accuracy = 0.6970, Val_loss =1.1830 , val_acc =0.5244
id 1016 epoch 68 index 19, Loss: 0.8794, accuracy = 0.7061, Val_loss =1.1172 , val_acc =0.5366
id 1016 epoch 69 index 19, Loss: 0.8834, accuracy = 0.6788, Val_loss =1.1050 , val_acc =0.5732
id 1016 epoch 70 index 19, Loss: 0.8665, accuracy = 0.6697, Val_loss =1.1812 , val_acc =0.5732
id 1016 epoch 71 index 19, Loss: 0.8496, accuracy = 0.7091, Val_loss =1.1789 , val_acc =0.6098
id 1016 epoch 72 index 19, Loss: 0.8224, accuracy 

id 1017 epoch 66 index 19, Loss: 0.8672, accuracy = 0.6697, Val_loss =1.6456 , val_acc =0.4756
id 1017 epoch 67 index 19, Loss: 0.8052, accuracy = 0.7091, Val_loss =1.7493 , val_acc =0.4756
id 1017 epoch 68 index 19, Loss: 0.7984, accuracy = 0.7152, Val_loss =1.6173 , val_acc =0.5000
id 1017 epoch 69 index 19, Loss: 0.8495, accuracy = 0.6636, Val_loss =1.5533 , val_acc =0.4390
id 1017 epoch 70 index 19, Loss: 0.8108, accuracy = 0.7242, Val_loss =1.5411 , val_acc =0.4878
id 1017 epoch 71 index 19, Loss: 0.8269, accuracy = 0.6818, Val_loss =1.5048 , val_acc =0.5000
id 1017 epoch 72 index 19, Loss: 0.7149, accuracy = 0.7273, Val_loss =1.5732 , val_acc =0.5122
id 1017 epoch 73 index 19, Loss: 0.8000, accuracy = 0.7212, Val_loss =1.7257 , val_acc =0.4390
id 1017 epoch 74 index 19, Loss: 0.8014, accuracy = 0.7030, Val_loss =1.8268 , val_acc =0.4512
id 1017 epoch 75 index 19, Loss: 0.7722, accuracy = 0.7515, Val_loss =1.7743 , val_acc =0.4390
id 1017 epoch 76 index 19, Loss: 0.7512, accuracy 

id 1018 epoch 70 index 19, Loss: 0.7487, accuracy = 0.7273, Val_loss =0.9829 , val_acc =0.6220
id 1018 epoch 71 index 19, Loss: 0.6986, accuracy = 0.7364, Val_loss =0.8681 , val_acc =0.7195
id 1018 epoch 72 index 19, Loss: 0.7664, accuracy = 0.7182, Val_loss =0.8596 , val_acc =0.7073
id 1018 epoch 73 index 19, Loss: 0.7291, accuracy = 0.7303, Val_loss =0.8745 , val_acc =0.6585
id 1018 epoch 74 index 19, Loss: 0.7226, accuracy = 0.7364, Val_loss =0.8927 , val_acc =0.7073
id 1018 epoch 75 index 19, Loss: 0.7898, accuracy = 0.6939, Val_loss =0.8423 , val_acc =0.6829
id 1018 epoch 76 index 19, Loss: 0.7682, accuracy = 0.7091, Val_loss =0.9091 , val_acc =0.6098
id 1018 epoch 77 index 19, Loss: 0.7326, accuracy = 0.7182, Val_loss =0.9840 , val_acc =0.6220
id 1018 epoch 78 index 19, Loss: 0.7565, accuracy = 0.7485, Val_loss =0.9036 , val_acc =0.7317
id 1018 epoch 79 index 19, Loss: 0.7535, accuracy = 0.7121, Val_loss =1.0167 , val_acc =0.6463
[[ 9  1  0  4  0  0]
 [ 0 10  0  0  1  3]
 [ 1  1 

id 1019 epoch 74 index 19, Loss: 0.7450, accuracy = 0.7262, Val_loss =1.1222 , val_acc =0.5921
id 1019 epoch 75 index 19, Loss: 0.7393, accuracy = 0.7470, Val_loss =1.2189 , val_acc =0.5395
id 1019 epoch 76 index 19, Loss: 0.6849, accuracy = 0.7470, Val_loss =1.1875 , val_acc =0.6184
id 1019 epoch 77 index 19, Loss: 0.7412, accuracy = 0.7202, Val_loss =1.1710 , val_acc =0.5658
id 1019 epoch 78 index 19, Loss: 0.7340, accuracy = 0.7381, Val_loss =1.2778 , val_acc =0.5921
id 1019 epoch 79 index 19, Loss: 0.7558, accuracy = 0.7232, Val_loss =1.3608 , val_acc =0.5263
[[10  0  0  2  1  0]
 [ 1  7  2  0  2  1]
 [ 0  1  1  0  5  6]
 [ 0  1  3  3  5  1]
 [ 0  0  0  0 11  0]
 [ 0  0  0  0  7  6]]
0.5
X_train: (7360, 369, 20)
X_test: (82, 369, 20)
y_train (7360, 6)
y_test (82, 6)
id 1020 epoch 0 index 19, Loss: 1.4936, accuracy = 0.3879, Val_loss =1.4965 , val_acc =0.4024
id 1020 epoch 1 index 19, Loss: 1.4941, accuracy = 0.3848, Val_loss =1.6362 , val_acc =0.3659
id 1020 epoch 2 index 19, Loss:

id 1020 epoch 79 index 19, Loss: 0.7690, accuracy = 0.7394, Val_loss =1.0116 , val_acc =0.6585
[[ 8  4  0  0  2  0]
 [ 0  7  0  0  2  5]
 [ 0  1  3  2  2  6]
 [ 0  3  2  9  0  0]
 [ 0  0  0  0 10  2]
 [ 0  1  0  0  0 13]]
0.6097560975609756
X_train: (7360, 369, 20)
X_test: (82, 369, 20)
y_train (7360, 6)
y_test (82, 6)
id 1021 epoch 0 index 19, Loss: 1.5732, accuracy = 0.3636, Val_loss =1.7013 , val_acc =0.3171
id 1021 epoch 1 index 19, Loss: 1.4762, accuracy = 0.3455, Val_loss =1.6237 , val_acc =0.3049
id 1021 epoch 2 index 19, Loss: 1.3550, accuracy = 0.4667, Val_loss =1.5347 , val_acc =0.4024
id 1021 epoch 3 index 19, Loss: 1.3538, accuracy = 0.4576, Val_loss =1.5659 , val_acc =0.3902
id 1021 epoch 4 index 19, Loss: 1.3035, accuracy = 0.4758, Val_loss =1.5888 , val_acc =0.3659
id 1021 epoch 5 index 19, Loss: 1.2887, accuracy = 0.4970, Val_loss =1.4383 , val_acc =0.4268
id 1021 epoch 6 index 19, Loss: 1.2683, accuracy = 0.5121, Val_loss =1.5281 , val_acc =0.3902
id 1021 epoch 7 index